import { DEFAULT_WHITELIST, LEGACY_OVERALL, LEGACY_LEAGUE_STATS, findCanonicalLeague } from './league-data.js';

const DEFAULTS={enabled:true,minMinute:23,maxMinute:32,maxGoals:0,minSot:1,minXg:0.50,whitelist:DEFAULT_WHITELIST,whitelistSeedVersion:1,whitelistCustomized:false,alerts:[],candidates:{},lastLiveHeartbeat:null,telegramBotToken:'',telegramChatId:'',liveLabApiUrl:'',liveLabIngestKey:'',apiLastError:'',chromeNotification:true,telegramLastError:''};
const cfg=async()=>({...DEFAULTS,...await chrome.storage.local.get(DEFAULTS)});
const keyOf=m=>m.id||`${m.home}|${m.away}`.toLowerCase().replace(/\s+/g,'-');

async function saveAlert(alert){const s=await cfg();await chrome.storage.local.set({alerts:[alert,...(s.alerts||[])].slice(0,500)});}
async function notifyChrome(title,message,id=`ll-${Date.now()}`){const s=await cfg();if(!s.chromeNotification)return;await chrome.notifications.create(id,{type:'basic',iconUrl:'icons/icon128.png',title,message,priority:2,requireInteraction:true});}
async function sendTelegram(text){const s=await cfg();if(!s.telegramBotToken||!s.telegramChatId)throw new Error('Telegram non configurato: inserisci Bot Token e Chat ID.');const response=await fetch(`https://api.telegram.org/bot${s.telegramBotToken}/sendMessage`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({chat_id:s.telegramChatId,text,disable_web_page_preview:true})});const data=await response.json().catch(()=>({}));if(!response.ok||data?.ok===false)throw new Error(data?.description||`Telegram HTTP ${response.status}`);return data;}
const pair=(a,b,d=0)=>Number.isFinite(Number(a))&&Number.isFinite(Number(b))?`${Number(a).toFixed(d)} - ${Number(b).toFixed(d)}`:null;

function flagForLeague(league=''){const x=league.toLowerCase();const map=[[/australia/,'🇦🇺'],[/austria/,'🇦🇹'],[/belgium/,'🇧🇪'],[/germany/,'🇩🇪'],[/italy|itália/,'🇮🇹'],[/japan/,'🇯🇵'],[/netherlands/,'🇳🇱'],[/spain/,'🇪🇸'],[/england|scotland|wales/,'🇬🇧'],[/france/,'🇫🇷'],[/portugal/,'🇵🇹'],[/sweden/,'🇸🇪'],[/norway/,'🇳🇴'],[/poland/,'🇵🇱'],[/peru/,'🇵🇪'],[/afc|fifa|world cup/,'🌐']];for(const[re,f]of map)if(re.test(x))return f;return'⚽';}

async function evaluateRemote(m){const s=await cfg();if(!s.liveLabApiUrl)return{ok:false,error:'Live Lab Web non configurato'};try{const response=await fetch(`${s.liveLabApiUrl.replace(/\/$/,'')}/api/ingest`,{method:'POST',headers:{'Content-Type':'application/json',...(s.liveLabIngestKey?{'x-live-lab-key':s.liveLabIngestKey}:{})},body:JSON.stringify({matchKey:m.key,matchDate:(()=>{const d=new Date();return`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`})(),league:m.canonicalLeague||m.league,home:m.home,away:m.away,minute:m.minute,homeScore:m.homeScore??0,awayScore:m.awayScore??0,xgHome:m.xgHome,xgAway:m.xgAway,sotHome:m.sotHome,sotAway:m.sotAway,attacksHome:m.attacksHome,attacksAway:m.attacksAway,dangerousHome:m.dangerousHome,dangerousAway:m.dangerousAway,possessionHome:m.possessionHome,possessionAway:m.possessionAway,redCardsHome:m.redCardsHome,redCardsAway:m.redCardsAway,sourceUrl:m.url||''})});const data=await response.json().catch(()=>({}));if(!response.ok||data?.ok===false)throw new Error(data?.error||`Live Lab HTTP ${response.status}`);await chrome.storage.local.set({apiLastError:''});return{ok:true,...data};}catch(err){const e=String(err?.message||err);await chrome.storage.local.set({apiLastError:e});return{ok:false,error:e};}}

function buildTelegramAlert(m,result){const e=result.engine||{},p=e.primary||{};const lines=[`🚨 LIVE LAB · ${e.tier||'SIGNAL'}`,``,`${p.label||'🔥 Strategy Radar'} · ${p.score??'—'}/100`,`${flagForLeague(m.canonicalLeague||m.league)} ${m.canonicalLeague||m.league||'Campionato'}`,`${m.home} vs ${m.away}`,`${m.minute}' · ${m.homeScore??0}-${m.awayScore??0}`,``];
  if(pair(m.xgHome,m.xgAway,2))lines.push(`xG: ${pair(m.xgHome,m.xgAway,2)}`);if(pair(m.sotHome,m.sotAway,0))lines.push(`SOT: ${pair(m.sotHome,m.sotAway,0)}`);if(pair(m.possessionHome,m.possessionAway,0))lines.push(`Possesso: ${pair(m.possessionHome,m.possessionAway,0)}%`);
  if(e.delta)lines.push(`ΔxG: +${Number((e.delta.xgHome||0)+(e.delta.xgAway||0)).toFixed(2)}`);
  const top=(e.signals||[]).filter(x=>x.score>=65).slice(0,3);if(top.length){lines.push('',`Radar: ${top.map(x=>`${x.label.replace(/^.. /,'')} ${x.score}`).join(' · ')}`);}
  if(p.reasons?.length)lines.push(`Motivi: ${p.reasons.slice(0,4).join(' · ')}`);
  lines.push('',`🔮 Forebet RE: ${result.gate?.predictedScore||'N/D'} ${result.gate?.status==='PASS'?'✅':result.gate?.status==='BLOCK'?'🚫':''}`,'','Verifica quota e situazione live prima dell’ingresso.');return lines.join('\n');}

async function handleLiveCandidate(m){const s=await cfg();if(!s.enabled)return;const canonicalLeague=findCanonicalLeague(m.league,s.whitelist||DEFAULT_WHITELIST);if(!canonicalLeague)return;const key=keyOf(m),now=Date.now(),existing=s.candidates?.[key];if(existing&&now-(existing.lastCheckAt||existing.firstSeen||0)<3*60*1000)return;const candidate={...m,canonicalLeague,key,firstSeen:existing?.firstSeen||now,lastCheckAt:now,status:'checking-stats'};await chrome.storage.local.set({candidates:{...(s.candidates||{}),[key]:candidate},lastLiveHeartbeat:now});if(m.url){const statsUrl=m.url.includes('#')?m.url:`${m.url}#/match-summary/match-statistics/0`;const tab=await chrome.tabs.create({url:statsUrl,active:false});await chrome.storage.session.set({[`tab:${tab.id}`]:{key,createdAt:now}});setTimeout(async()=>{try{await chrome.tabs.remove(tab.id);}catch(_){}},25000);}}

async function handleStats(payload,sender){const s=await cfg();if(!s.enabled)return;let key=payload.key;if(!key&&sender?.tab?.id){const sess=await chrome.storage.session.get(`tab:${sender.tab.id}`);key=sess?.[`tab:${sender.tab.id}`]?.key;}if(!key)key=keyOf(payload);const candidate=s.candidates?.[key]||payload;if(!candidate)return;const updated={...candidate,...payload,canonicalLeague:candidate.canonicalLeague,key,checkedAt:Date.now(),status:'evaluated'};await chrome.storage.local.set({candidates:{...(s.candidates||{}),[key]:updated}});
  const result=await evaluateRemote(updated);if(!result.ok)return;if(!result.engine||result.engine.tier==='NONE'||result.engine.tier==='WATCH')return;
  const alert={type:result.engine.blocked?'BLOCKED':'SIGNAL',ts:Date.now(),key,engine:result.engine,forebetGate:result.gate,home:updated.home,away:updated.away,league:updated.league,canonicalLeague:updated.canonicalLeague,minute:updated.minute,score:`${updated.homeScore??0}-${updated.awayScore??0}`,xgHome:updated.xgHome,xgAway:updated.xgAway,sotHome:updated.sotHome,sotAway:updated.sotAway,url:updated.url||payload.url||''};alert.text=buildTelegramAlert(updated,result);await saveAlert(alert);
  if(result.engine.blocked||result.gate?.status==='BLOCK'){await notifyChrome('🚫 Live Lab — segnale bloccato da Forebet',`${updated.home} - ${updated.away}\n${result.engine.primary?.label||'Radar'} ${result.engine.primary?.score||''}/100`);return;}
  if(result.shouldAlert===false)return;let telegramOk=false;try{await sendTelegram(alert.text);telegramOk=true;await chrome.storage.local.set({telegramLastError:''});}catch(err){await chrome.storage.local.set({telegramLastError:String(err?.message||err)});}await notifyChrome(telegramOk?'🚨 Live Lab — Strategy Radar':'⚠️ Live Lab — Telegram non inviato',telegramOk?`${updated.home} - ${updated.away}\n${result.engine.primary?.label||'Signal'} ${result.engine.primary?.score||''}/100`:'Apri Live Lab e controlla la configurazione Telegram.');}

chrome.runtime.onInstalled.addListener(async()=>{const current=await chrome.storage.local.get(null);const shouldSeed=!current.whitelistCustomized&&(!Array.isArray(current.whitelist)||current.whitelist.length===0||!current.whitelistSeedVersion);await chrome.storage.local.set({...DEFAULTS,...current,...(shouldSeed?{whitelist:DEFAULT_WHITELIST,whitelistSeedVersion:1}:{})});});
chrome.runtime.onMessage.addListener((msg,sender,sendResponse)=>{if(msg?.type==='LIVE_HEARTBEAT')chrome.storage.local.set({lastLiveHeartbeat:Date.now()});if(msg?.type==='LIVE_CANDIDATE')handleLiveCandidate(msg.match,sender);if(msg?.type==='MATCH_STATS')handleStats(msg.data,sender);if(msg?.type==='TEST_TELEGRAM'){sendTelegram(`🚨 Live Lab 0.5.0 — test\n\nTelegram configurato.\nStrategy Radar: Goal Pressure · Late Goal · Equalizer · Favorite Push.\nSnowball/Under: esclusi.\nWhitelist: ${DEFAULT_WHITELIST.length} campionati.`).then(()=>{chrome.storage.local.set({telegramLastError:''});sendResponse({ok:true});}).catch(err=>{chrome.storage.local.set({telegramLastError:String(err?.message||err)});sendResponse({ok:false,error:String(err?.message||err)});});return true;}});
chrome.notifications.onClicked.addListener(async()=>{const s=await cfg();const latest=(s.alerts||[]).find(a=>a.url);if(latest?.url)chrome.tabs.create({url:latest.url,active:true});});
