import { DEFAULT_WHITELIST, LEGACY_OVERALL, LEGACY_LEAGUE_STATS, findCanonicalLeague } from './league-data.js';

const DEFAULTS={
  enabled:true,minMinute:23,maxMinute:32,maxGoals:0,minSot:1,minXg:0.50,
  whitelist:DEFAULT_WHITELIST,whitelistSeedVersion:1,whitelistCustomized:false,
  alerts:[],candidates:{},activePaper:{},paperQuoteAt:{},paperCloseNotified:{},lastLiveHeartbeat:null,
  telegramBotToken:'',telegramChatId:'',liveLabApiUrl:'',liveLabIngestKey:'',apiLastError:'',
  chromeNotification:true,telegramLastError:'',paperAuto:true,betfairAppKey:'',betfairLastError:''
};
const cfg=async()=>({...DEFAULTS,...await chrome.storage.local.get(DEFAULTS)});
const keyOf=m=>m.id||`${m.home}|${m.away}`.toLowerCase().replace(/\s+/g,'-');

const STRATEGY_META={
  GOAL_PRESSURE:{emoji:'🔥',name:'GOAL PRESSURE',icon:'icons/goal-pressure.svg'},
  LATE_GOAL:{emoji:'⚡',name:'LATE GOAL',icon:'icons/late-goal.svg'},
  EQUALIZER:{emoji:'🔄',name:'EQUALIZER',icon:'icons/equalizer.svg'},
  FAVORITE_PUSH:{emoji:'👑',name:'FAVORITE PUSH',icon:'icons/favorite-push.svg'}
};
function strategyMeta(code){return STRATEGY_META[code]||{emoji:'🚨',name:'STRATEGY RADAR',icon:'icons/icon128.png'};}

async function saveAlert(alert){const s=await cfg();await chrome.storage.local.set({alerts:[alert,...(s.alerts||[])].slice(0,500)});}
async function notifyChrome(title,message,id=`ll-${Date.now()}`,iconUrl='icons/icon128.png'){const s=await cfg();if(!s.chromeNotification)return;await chrome.notifications.create(id,{type:'basic',iconUrl,title,message,priority:2,requireInteraction:true});}
async function sendTelegram(text){const s=await cfg();if(!s.telegramBotToken||!s.telegramChatId)throw new Error('Telegram non configurato: inserisci Bot Token e Chat ID.');const response=await fetch(`https://api.telegram.org/bot${s.telegramBotToken}/sendMessage`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({chat_id:s.telegramChatId,text,disable_web_page_preview:true})});const data=await response.json().catch(()=>({}));if(!response.ok||data?.ok===false)throw new Error(data?.description||`Telegram HTTP ${response.status}`);return data;}
const pair=(a,b,d=0)=>Number.isFinite(Number(a))&&Number.isFinite(Number(b))?`${Number(a).toFixed(d)} - ${Number(b).toFixed(d)}`:null;

function flagForLeague(league=''){const x=league.toLowerCase();const map=[[/australia/,'🇦🇺'],[/austria/,'🇦🇹'],[/belgium/,'🇧🇪'],[/germany/,'🇩🇪'],[/italy|itália/,'🇮🇹'],[/japan/,'🇯🇵'],[/netherlands/,'🇳🇱'],[/spain/,'🇪🇸'],[/england|scotland|wales/,'🇬🇧'],[/france/,'🇫🇷'],[/portugal/,'🇵🇹'],[/sweden/,'🇸🇪'],[/norway/,'🇳🇴'],[/poland/,'🇵🇱'],[/peru/,'🇵🇪'],[/afc|fifa|world cup/,'🌐']];for(const[re,f]of map)if(re.test(x))return f;return'⚽';}

async function evaluateRemote(m){const s=await cfg();if(!s.liveLabApiUrl)return{ok:false,error:'Live Lab Web non configurato'};try{const response=await fetch(`${s.liveLabApiUrl.replace(/\/$/,'')}/api/ingest`,{method:'POST',headers:{'Content-Type':'application/json',...(s.liveLabIngestKey?{'x-live-lab-key':s.liveLabIngestKey}:{})},body:JSON.stringify({matchKey:m.key,matchDate:(()=>{const d=new Date();return`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`})(),league:m.canonicalLeague||m.league,home:m.home,away:m.away,minute:m.minute,homeScore:m.homeScore??0,awayScore:m.awayScore??0,xgHome:m.xgHome,xgAway:m.xgAway,sotHome:m.sotHome,sotAway:m.sotAway,attacksHome:m.attacksHome,attacksAway:m.attacksAway,dangerousHome:m.dangerousHome,dangerousAway:m.dangerousAway,possessionHome:m.possessionHome,possessionAway:m.possessionAway,redCardsHome:m.redCardsHome,redCardsAway:m.redCardsAway,sourceUrl:m.url||''})});const data=await response.json().catch(()=>({}));if(!response.ok||data?.ok===false)throw new Error(data?.error||`Live Lab HTTP ${response.status}`);await chrome.storage.local.set({apiLastError:''});return{ok:true,...data};}catch(err){const e=String(err?.message||err);await chrome.storage.local.set({apiLastError:e});return{ok:false,error:e};}}

function norm(s=''){return String(s).normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().replace(/[^a-z0-9]+/g,' ').replace(/\b(fc|cf|calcio|football|club|deportivo|sporting|united|city)\b/g,' ').replace(/\s+/g,' ').trim();}
function eventMatchScore(eventName,home,away){const e=norm(eventName),h=norm(home),a=norm(away);let score=0;for(const t of h.split(' ').filter(x=>x.length>2))if(e.includes(t))score+=2;for(const t of a.split(' ').filter(x=>x.length>2))if(e.includes(t))score+=2;if(e.includes(h))score+=5;if(e.includes(a))score+=5;return score;}
async function betfairSessionToken(){for(const url of ['https://www.betfair.it','https://www.betfair.com']){try{const c=await chrome.cookies.get({url,name:'ssoid'});if(c?.value)return c.value;}catch(_){}}return'';}
async function betfairCall(path,body){const s=await cfg();if(!s.betfairAppKey)throw new Error('Betfair App Key mancante');const token=await betfairSessionToken();if(!token)throw new Error('Sessione Betfair non trovata: accedi a Betfair in Chrome');const r=await fetch(`https://api.betfair.com/exchange/betting/rest/v1.0/${path}/`,{method:'POST',headers:{'Content-Type':'application/json','X-Application':s.betfairAppKey,'X-Authentication':token},body:JSON.stringify(body)});const data=await r.json().catch(()=>null);if(!r.ok||!data)throw new Error(data?.faultstring||data?.error?.message||`Betfair HTTP ${r.status}`);return data;}
async function findGoalPressureQuote(m){
  const catalogue=await betfairCall('listMarketCatalogue',{filter:{eventTypeIds:['1'],inPlayOnly:true,marketTypeCodes:['OVER_UNDER_15']},marketProjection:['EVENT','RUNNER_DESCRIPTION','MARKET_START_TIME'],sort:'FIRST_TO_START',maxResults:'200',locale:'en'});
  if(!Array.isArray(catalogue)||!catalogue.length)throw new Error('Nessun mercato Over 1.5 in-play trovato');
  const ranked=catalogue.map(x=>({x,score:eventMatchScore(x.event?.name||'',m.home,m.away)})).sort((a,b)=>b.score-a.score);
  const market=ranked[0]?.score>=4?ranked[0].x:null;if(!market)throw new Error('Partita non riconosciuta su Betfair');
  const over=(market.runners||[]).find(r=>/over\s*1[\.,]5/i.test(r.runnerName||''))||(market.runners||[]).find(r=>/over/i.test(r.runnerName||''));
  if(!over)throw new Error('Selezione Over 1.5 non trovata');
  const books=await betfairCall('listMarketBook',{marketIds:[market.marketId],priceProjection:{priceData:['EX_BEST_OFFERS'],virtualise:true,exBestOffersOverrides:{bestPricesDepth:3,rollupModel:'STAKE',rollupLimit:2}}});
  const runner=books?.[0]?.runners?.find(r=>String(r.selectionId)===String(over.selectionId));if(!runner)throw new Error('Quota Over 1.5 non disponibile');
  const back=runner.ex?.availableToBack?.[0]?.price??null,lay=runner.ex?.availableToLay?.[0]?.price??null;
  return {marketId:market.marketId,marketName:market.marketName||'Over/Under 1.5 Goals',selectionId:String(over.selectionId),selectionName:over.runnerName||'Over 1.5 Goals',backPrice:back,layPrice:lay,eventName:market.event?.name||''};
}
async function postPaperQuote(m,engine,quote){const s=await cfg();if(!s.liveLabApiUrl)return{ok:false,error:'Live Lab Web non configurato'};const r=await fetch(`${s.liveLabApiUrl.replace(/\/$/,'')}/api/paper/quote`,{method:'POST',headers:{'Content-Type':'application/json',...(s.liveLabIngestKey?{'x-live-lab-key':s.liveLabIngestKey}:{})},body:JSON.stringify({matchKey:m.key,strategyCode:engine.primary?.code,marketId:quote.marketId,marketName:quote.marketName,selectionId:quote.selectionId,selectionName:quote.selectionName,backPrice:quote.backPrice,layPrice:quote.layPrice,minute:m.minute,homeScore:m.homeScore??0,awayScore:m.awayScore??0})});const data=await r.json().catch(()=>({}));if(!r.ok||data?.ok===false)throw new Error(data?.error||`Paper HTTP ${r.status}`);return data;}
async function paperCycle(m,engine,force=false){const s=await cfg();if(!s.paperAuto||engine?.primary?.code!=='GOAL_PRESSURE')return null;const key=keyOf(m),now=Date.now(),last=s.paperQuoteAt?.[key]||0;if(!force&&now-last<30000)return null;await chrome.storage.local.set({paperQuoteAt:{...(s.paperQuoteAt||{}),[key]:now}});try{const quote=await findGoalPressureQuote(m);const result=await postPaperQuote({...m,key},engine,quote);await chrome.storage.local.set({betfairLastError:''});const paper=result.paper||null;if(paper?.tradeId&&paper.status!=='CLOSED'){const fresh=await cfg();await chrome.storage.local.set({activePaper:{...(fresh.activePaper||{}),[key]:{strategyCode:'GOAL_PRESSURE',tradeId:paper.tradeId,home:m.home,away:m.away,lastHomeScore:m.homeScore??0,lastAwayScore:m.awayScore??0}}});}if(paper?.status==='CLOSED'){const fresh=await cfg();const active={...(fresh.activePaper||{})};delete active[key];await chrome.storage.local.set({activePaper:active});}return {...paper,quote};}catch(err){const e=String(err?.message||err);await chrome.storage.local.set({betfairLastError:e});return {status:'ERROR',error:e};}}
function paperLines(paper){if(!paper)return[];if(paper.status==='ERROR')return['',`🧪 PAPER AUTO: non eseguito · ${paper.error}`];if(paper.status==='WAITING_PRICE')return['','🧪 PAPER AUTO: in attesa quota Exchange'];if(paper.status==='WAITING_STRATEGY_RULE')return['','🧪 PAPER AUTO: regola di esecuzione non ancora attiva per questa strategia'];if(paper.status==='OPEN'){const orders=(paper.orders||[]).map(o=>`${o.tranche}) €${Number(o.stake).toFixed(2)} @${Number(o.targetPrice).toFixed(2)} ${o.status==='MATCHED'?'✓':'…'}`).join(' · ');return['',`🧪 PAPER AUTO · stake ${Number(paper.stakePct).toFixed(1)}% = €${Number(paper.stakeTotal).toFixed(2)}`,`Ladder: ${orders}`];}if(paper.status==='CLOSED')return['',`🧪 PAPER CHIUSO · P/L ${Number(paper.netPnl)>=0?'+':''}€${Number(paper.netPnl).toFixed(2)} · cassa €${Number(paper.bankrollAfter).toFixed(2)}`];return[];}

function buildTelegramAlert(m,result,paper){const e=result.engine||{},p=e.primary||{},meta=strategyMeta(p.code);const lines=[`${meta.emoji} LIVE LAB · ${meta.name} · TIER ${e.tier||'SIGNAL'}`,'',`${meta.emoji} ${meta.name} · ${p.score??'—'}/100`,`${flagForLeague(m.canonicalLeague||m.league)} ${m.canonicalLeague||m.league||'Campionato'}`,`${m.home} vs ${m.away}`,`${m.minute}' · ${m.homeScore??0}-${m.awayScore??0}`,''];if(pair(m.xgHome,m.xgAway,2))lines.push(`xG: ${pair(m.xgHome,m.xgAway,2)}`);if(pair(m.sotHome,m.sotAway,0))lines.push(`SOT: ${pair(m.sotHome,m.sotAway,0)}`);if(pair(m.possessionHome,m.possessionAway,0))lines.push(`Possesso: ${pair(m.possessionHome,m.possessionAway,0)}%`);if(e.delta)lines.push(`ΔxG: +${Number((e.delta.xgHome||0)+(e.delta.xgAway||0)).toFixed(2)}`);const top=(e.signals||[]).filter(x=>x.score>=65).slice(0,3);if(top.length)lines.push('',`Radar: ${top.map(x=>`${strategyMeta(x.code).emoji} ${strategyMeta(x.code).name} ${x.score}`).join(' · ')}`);if(p.reasons?.length)lines.push(`Motivi: ${p.reasons.slice(0,4).join(' · ')}`);lines.push('',`🔮 Forebet RE: ${result.gate?.predictedScore||'N/D'} ${result.gate?.status==='PASS'?'✅':result.gate?.status==='BLOCK'?'🚫':''}`,...paperLines(paper),'','Verifica quota e situazione live prima dell’ingresso reale.');return lines.join('\n');}

async function handleLiveCandidate(m){const s=await cfg();if(!s.enabled)return;const canonicalLeague=findCanonicalLeague(m.league,s.whitelist||DEFAULT_WHITELIST);if(!canonicalLeague)return;const key=keyOf(m),now=Date.now(),existing=s.candidates?.[key];if(existing&&now-(existing.lastCheckAt||existing.firstSeen||0)<3*60*1000)return;const candidate={...m,canonicalLeague,key,firstSeen:existing?.firstSeen||now,lastCheckAt:now,status:'checking-stats'};await chrome.storage.local.set({candidates:{...(s.candidates||{}),[key]:candidate},lastLiveHeartbeat:now});if(m.url){const statsUrl=m.url.includes('#')?m.url:`${m.url}#/match-summary/match-statistics/0`;const tab=await chrome.tabs.create({url:statsUrl,active:false});await chrome.storage.session.set({[`tab:${tab.id}`]:{key,createdAt:now}});setTimeout(async()=>{try{await chrome.tabs.remove(tab.id);}catch(_){}},25000);}}

async function handleStats(payload,sender){const s=await cfg();if(!s.enabled)return;let key=payload.key;if(!key&&sender?.tab?.id){const sess=await chrome.storage.session.get(`tab:${sender.tab.id}`);key=sess?.[`tab:${sender.tab.id}`]?.key;}if(!key)key=keyOf(payload);const candidate=s.candidates?.[key]||payload;if(!candidate)return;const updated={...candidate,...payload,canonicalLeague:candidate.canonicalLeague,key,checkedAt:Date.now(),status:'evaluated'};await chrome.storage.local.set({candidates:{...(s.candidates||{}),[key]:updated}});const result=await evaluateRemote(updated);if(!result.ok)return;if(!result.engine||result.engine.tier==='NONE'||result.engine.tier==='WATCH')return;let paper=null;if(!result.engine.blocked&&result.gate?.status!=='BLOCK')paper=await paperCycle(updated,result.engine,true);const alert={type:result.engine.blocked?'BLOCKED':'SIGNAL',ts:Date.now(),key,engine:result.engine,forebetGate:result.gate,paper,home:updated.home,away:updated.away,league:updated.league,canonicalLeague:updated.canonicalLeague,minute:updated.minute,score:`${updated.homeScore??0}-${updated.awayScore??0}`,xgHome:updated.xgHome,xgAway:updated.xgAway,sotHome:updated.sotHome,sotAway:updated.sotAway,url:updated.url||payload.url||''};alert.text=buildTelegramAlert(updated,result,paper);if(result.shouldAlert!==false)await saveAlert(alert);const meta=strategyMeta(result.engine.primary?.code);if(result.engine.blocked||result.gate?.status==='BLOCK'){if(result.shouldAlert!==false)await notifyChrome('🚫 Live Lab — segnale bloccato da Forebet',`${updated.home} - ${updated.away}\n${meta.emoji} ${meta.name} ${result.engine.primary?.score||''}/100`,undefined,meta.icon);return;}if(result.shouldAlert===false)return;let telegramOk=false;try{await sendTelegram(alert.text);telegramOk=true;await chrome.storage.local.set({telegramLastError:''});}catch(err){await chrome.storage.local.set({telegramLastError:String(err?.message||err)});}await notifyChrome(telegramOk?`${meta.emoji} Live Lab — ${meta.name}`:'⚠️ Live Lab — Telegram non inviato',telegramOk?`${updated.home} - ${updated.away}\n${result.engine.primary?.score||''}/100 · Tier ${result.engine.tier}`:'Apri Live Lab e controlla la configurazione Telegram.',undefined,meta.icon);}

async function handleLiveScore(m){const s=await cfg();const key=keyOf(m),active=s.activePaper?.[key];if(!active||active.strategyCode!=='GOAL_PRESSURE')return;const now=Date.now(),last=s.paperQuoteAt?.[key]||0;const scoreChanged=Number(active.lastHomeScore)!==Number(m.homeScore)||Number(active.lastAwayScore)!==Number(m.awayScore);if(!scoreChanged&&now-last<30000)return;const engine={primary:{code:'GOAL_PRESSURE'}};const paper=await paperCycle({...m,key},engine,scoreChanged);if(paper?.status==='CLOSED'){const fresh=await cfg();if(!fresh.paperCloseNotified?.[paper.tradeId]){const text=`🧪 PAPER AUTO · GOAL PRESSURE CHIUSO\n\n${m.home} vs ${m.away}\n${m.minute}' · ${m.homeScore}-${m.awayScore}\nStake usato: €${Number(paper.stakeFilled||0).toFixed(2)}\nQuota media: ${Number(paper.avgPrice||0).toFixed(2)}\nUscita lay: ${Number(paper.exitLayPrice||0).toFixed(2)}\nP/L netto: ${Number(paper.netPnl)>=0?'+':''}€${Number(paper.netPnl||0).toFixed(2)}\nCassa paper: €${Number(paper.bankrollAfter||0).toFixed(2)}`;try{await sendTelegram(text);}catch(_){}await chrome.storage.local.set({paperCloseNotified:{...(fresh.paperCloseNotified||{}),[paper.tradeId]:true}});}}else if(paper?.tradeId){const fresh=await cfg();await chrome.storage.local.set({activePaper:{...(fresh.activePaper||{}),[key]:{...active,lastHomeScore:m.homeScore,lastAwayScore:m.awayScore}}});}}

chrome.runtime.onInstalled.addListener(async()=>{const current=await chrome.storage.local.get(null);const shouldSeed=!current.whitelistCustomized&&(!Array.isArray(current.whitelist)||current.whitelist.length===0||!current.whitelistSeedVersion);await chrome.storage.local.set({...DEFAULTS,...current,...(shouldSeed?{whitelist:DEFAULT_WHITELIST,whitelistSeedVersion:1}:{})});});
chrome.runtime.onMessage.addListener((msg,sender,sendResponse)=>{if(msg?.type==='LIVE_HEARTBEAT')chrome.storage.local.set({lastLiveHeartbeat:Date.now()});if(msg?.type==='LIVE_CANDIDATE')handleLiveCandidate(msg.match,sender);if(msg?.type==='LIVE_SCORE')handleLiveScore(msg.match);if(msg?.type==='MATCH_STATS')handleStats(msg.data,sender);if(msg?.type==='TEST_TELEGRAM'){sendTelegram(`🚨 Live Lab 0.6.0 — test\n\n🔥 Goal Pressure\n⚡ Late Goal\n🔄 Equalizer\n👑 Favorite Push\n\n🧪 Paper Exchange AUTO attivo\nGoal Pressure: 4 tranche · 25 tick · stake max 10%\n\nTelegram configurato.`).then(()=>{chrome.storage.local.set({telegramLastError:''});sendResponse({ok:true});}).catch(err=>{chrome.storage.local.set({telegramLastError:String(err?.message||err)});sendResponse({ok:false,error:String(err?.message||err)});});return true;}if(msg?.type==='TEST_BETFAIR'){(async()=>{try{const token=await betfairSessionToken();if(!token)throw new Error('Accedi prima a Betfair in Chrome');const s=await cfg();if(!s.betfairAppKey)throw new Error('Inserisci Betfair App Key');await betfairCall('listEventTypes',{filter:{}});await chrome.storage.local.set({betfairLastError:''});sendResponse({ok:true});}catch(err){const e=String(err?.message||err);await chrome.storage.local.set({betfairLastError:e});sendResponse({ok:false,error:e});}})();return true;}});
chrome.notifications.onClicked.addListener(async()=>{const s=await cfg();const latest=(s.alerts||[]).find(a=>a.url);if(latest?.url)chrome.tabs.create({url:latest.url,active:true});});
