export const LEGACY_OVERALL={picks:106,resolved:101,hits:75,misses:26,pending:5,strike:74,fairOdd:1.35};
export const LEGACY_LEAGUE_STATS:Record<string,{picks:number;strike:number;fairOdd:number|null}>={
'England League 1':{picks:11,strike:64,fairOdd:1.56},'Japan J-League':{picks:11,strike:90,fairOdd:1.11},'England League 2':{picks:10,strike:78,fairOdd:1.28},'Poland Ekstraklasa':{picks:8,strike:75,fairOdd:1.33},'Peru Liga 1':{picks:8,strike:86,fairOdd:1.16},'Sweden Allsvenskan':{picks:7,strike:57,fairOdd:1.75},'Italy Serie A':{picks:7,strike:71,fairOdd:1.41},'Portugal Primeira Liga':{picks:6,strike:67,fairOdd:1.49},'Denmark Superligaen':{picks:5,strike:80,fairOdd:1.25},'Belgium First Division A':{picks:5,strike:75,fairOdd:1.33},'England Championship':{picks:5,strike:60,fairOdd:1.67},'Netherlands Eerste Divisie':{picks:5,strike:80,fairOdd:1.25},'Germany Bundesliga II':{picks:4,strike:100,fairOdd:1.00},'Austria Bundesliga':{picks:4,strike:67,fairOdd:1.49},'Slovakia Super Liga':{picks:4,strike:75,fairOdd:1.33},'Italy Serie B':{picks:2,strike:50,fairOdd:2.00},'Netherlands Eredivisie':{picks:1,strike:100,fairOdd:1.00},'Switzerland Super League':{picks:1,strike:0,fairOdd:null},'Norway Eliteserien':{picks:1,strike:100,fairOdd:1.00},'Greece Super League 1':{picks:1,strike:100,fairOdd:1.00}};
export const WHITELIST=[
'Australia A-League','Austria 2. Liga','Austria Bundesliga','Belgium Cup','Belgium First Division A','Belgium Reserve League','Bosnia & Herzegovina Premier Liga','Bulgaria First League','Chile Primera Division','Croatia 1.HNL','Croatia 2.HNL','Czech Republic First League','Denmark Superligaen','Estonia Esiliiga','Estonia Meistriliiga','Finland Kakkonen Group A','Finland Kakkonen Group B','Finland Kakkonen Group C','Finland Kakkonnen Play-Offs','Finland Kolmonen','Finland Veikkausliiga','Finland Ykkonen','France National','Germany 3.Liga','Germany Bundesliga I','Germany Bundesliga II','Germany Bundesliga II Play-Offs','Germany Bundesliga Play-Offs','Greece Super League 1','Hungary NB I','Iceland Premier League','India I-League','Indonesia Liga 1','Northern Ireland Premier','Israel Premier League','Itália - Série B','Italy Serie A','Italy Serie B','Japan J-League','Latvia 1. Liga','Netherlands Eerste Divisie','Netherlands Eredivisie','Norway Division 1','Norway Eliteserien','Peru Liga 1','Poland Ekstraklasa','Portugal Primeira Liga','Romania Liga II','Saudi Arabia Premier League','Serbia Super Liga','Slovakia Super Liga','South Korea K League 1','South Korea K League 2','South Korea K-League 1','South Korea K-League 2','Spain Primera Liga','Sweden 1.div Norra','Sweden 1.div Södra','Sweden 2.div Norra Götaland','Sweden 2.div Norra Svealand','Sweden 2.div Norrland','Sweden 2.div Södra Götaland','Sweden 2.div Västra Götaland','Sweden Allsvenskan','Sweden Superettan','Switzerland Super League','Tunisia League 1','England Championship','England FA Cup','England League 1','England League 2','England National League','Scotland Championship','Scotland League One','Scotland League Two','Wales Premier League','AFC Asian Cup','AFC Asian Cup Qualifiers','AFC Champions League','AFC Champions League Qualification','FIFA Club World Cup'];
export const SAMPLE_ALERTS=[
{id:1,date:'13/09/2026',league:'Poland Ekstraklasa',match:'Pogon Szczecin – Wieczysta Krakow',minute:29,score:'0-0',xg:'0.4 - 0.6',sot:'2 - 1',forebet:'2-1',gate:'PASS',result:'2-1',outcome:'HIT'},
{id:2,date:'12/09/2026',league:'Japan J-League',match:'Kashima Antlers – Yokohama F. Marinos',minute:28,score:'0-0',xg:'0.3 - 0.4',sot:'2 - 1',forebet:'1-0',gate:'BLOCK',result:'1-0',outcome:'BLOCK'},
{id:3,date:'11/09/2026',league:'Peru Liga 1',match:'Alianza – Cusco',minute:31,score:'0-0',xg:'0.5 - 0.3',sot:'1 - 2',forebet:'0-2',gate:'PASS',result:'0-2',outcome:'HIT'}];
